/*
 * This file is generated by jOOQ.
 */
package com.model.rental.domains;


import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
// CHECK (((VALUE >= 1901) AND (VALUE <= 2155)))
public class Year {
}
