/*
 * This file is generated by jOOQ.
 */
package com.model.rental.tables;


import com.model.rental.DefaultSchema;
import com.model.rental.enums.MpaaRating;

import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmList extends TableImpl<Record> {

    private static final long serialVersionUID = 1420890637;

    /**
     * The reference instance of <code>film_list</code>
     */
    public static final FilmList FILM_LIST = new FilmList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>film_list.fid</code>.
     */
    public final TableField<Record, Integer> FID = createField(DSL.name("fid"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>film_list.title</code>.
     */
    public final TableField<Record, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>film_list.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>film_list.category</code>.
     */
    public final TableField<Record, String> CATEGORY = createField(DSL.name("category"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>film_list.price</code>.
     */
    public final TableField<Record, BigDecimal> PRICE = createField(DSL.name("price"), org.jooq.impl.SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>film_list.length</code>.
     */
    public final TableField<Record, Short> LENGTH = createField(DSL.name("length"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>film_list.rating</code>.
     */
    public final TableField<Record, MpaaRating> RATING = createField(DSL.name("rating"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(com.model.rental.enums.MpaaRating.class), this, "");

    /**
     * The column <code>film_list.actors</code>.
     */
    public final TableField<Record, String> ACTORS = createField(DSL.name("actors"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>film_list</code> table reference
     */
    public FilmList() {
        this(DSL.name("film_list"), null);
    }

    /**
     * Create an aliased <code>film_list</code> table reference
     */
    public FilmList(String alias) {
        this(DSL.name(alias), FILM_LIST);
    }

    /**
     * Create an aliased <code>film_list</code> table reference
     */
    public FilmList(Name alias) {
        this(alias, FILM_LIST);
    }

    private FilmList(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private FilmList(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FilmList(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, FILM_LIST);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public FilmList as(String alias) {
        return new FilmList(DSL.name(alias), this);
    }

    @Override
    public FilmList as(Name alias) {
        return new FilmList(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FilmList rename(String name) {
        return new FilmList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilmList rename(Name name) {
        return new FilmList(name, null);
    }
}
