/*
 * This file is generated by jOOQ.
 */
package com.model.rental.tables;


import com.model.rental.DefaultSchema;
import com.model.rental.Indexes;
import com.model.rental.Keys;
import com.model.rental.enums.MpaaRating;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Film extends TableImpl<Record> {

    private static final long serialVersionUID = 1763728416;

    /**
     * The reference instance of <code>film</code>
     */
    public static final Film FILM = new Film();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>film.film_id</code>.
     */
    public final TableField<Record, Integer> FILM_ID = createField(DSL.name("film_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('dvdrental.film_film_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>film.title</code>.
     */
    public final TableField<Record, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>film.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>film.release_year</code>.
     */
    public final TableField<Record, Integer> RELEASE_YEAR = createField(DSL.name("release_year"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>film.language_id</code>.
     */
    public final TableField<Record, Short> LANGUAGE_ID = createField(DSL.name("language_id"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>film.rental_duration</code>.
     */
    public final TableField<Record, Short> RENTAL_DURATION = createField(DSL.name("rental_duration"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("3", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>film.rental_rate</code>.
     */
    public final TableField<Record, BigDecimal> RENTAL_RATE = createField(DSL.name("rental_rate"), org.jooq.impl.SQLDataType.NUMERIC(4, 2).nullable(false).defaultValue(org.jooq.impl.DSL.field("4.99", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>film.length</code>.
     */
    public final TableField<Record, Short> LENGTH = createField(DSL.name("length"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>film.replacement_cost</code>.
     */
    public final TableField<Record, BigDecimal> REPLACEMENT_COST = createField(DSL.name("replacement_cost"), org.jooq.impl.SQLDataType.NUMERIC(5, 2).nullable(false).defaultValue(org.jooq.impl.DSL.field("19.99", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>film.rating</code>.
     */
    public final TableField<Record, MpaaRating> RATING = createField(DSL.name("rating"), org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("'G'::dvdrental.mpaa_rating", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(com.model.rental.enums.MpaaRating.class), this, "");

    /**
     * The column <code>film.last_update</code>.
     */
    public final TableField<Record, LocalDateTime> LAST_UPDATE = createField(DSL.name("last_update"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>film.special_features</code>.
     */
    public final TableField<Record, String[]> SPECIAL_FEATURES = createField(DSL.name("special_features"), org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<Record, Object> FULLTEXT = createField(DSL.name("fulltext"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\"").nullable(false), this, "");

    /**
     * Create a <code>film</code> table reference
     */
    public Film() {
        this(DSL.name("film"), null);
    }

    /**
     * Create an aliased <code>film</code> table reference
     */
    public Film(String alias) {
        this(DSL.name(alias), FILM);
    }

    /**
     * Create an aliased <code>film</code> table reference
     */
    public Film(Name alias) {
        this(alias, FILM);
    }

    private Film(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Film(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Film(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, FILM);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILM_FULLTEXT_IDX, Indexes.FILM_PKEY, Indexes.IDX_FK_LANGUAGE_ID, Indexes.IDX_TITLE);
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Keys.IDENTITY_FILM;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.FILM_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.FILM_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FILM__FILM_LANGUAGE_ID_FKEY);
    }

    public Language language() {
        return new Language(this, Keys.FILM__FILM_LANGUAGE_ID_FKEY);
    }

    @Override
    public Film as(String alias) {
        return new Film(DSL.name(alias), this);
    }

    @Override
    public Film as(Name alias) {
        return new Film(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Film rename(String name) {
        return new Film(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Film rename(Name name) {
        return new Film(name, null);
    }
}
