/*
 * This file is generated by jOOQ.
 */
package com.model.rental.routines;


import com.model.rental.DefaultSchema;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastDay extends AbstractRoutine<LocalDate> {

    private static final long serialVersionUID = -136437867;

    /**
     * The parameter <code>last_day.RETURN_VALUE</code>.
     */
    public static final Parameter<LocalDate> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter <code>last_day._1</code>.
     */
    public static final Parameter<LocalDateTime> _1 = Internal.createParameter("_1", org.jooq.impl.SQLDataType.LOCALDATETIME, false, true);

    /**
     * Create a new routine call instance
     */
    public LastDay() {
        super("last_day", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.LOCALDATE);

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(LocalDateTime value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public LastDay set__1(Field<LocalDateTime> field) {
        setField(_1, field);
        return this;
    }
}
