/*
 * This file is generated by jOOQ.
 */
package com.model.rental;


import com.model.rental.tables.Actor;
import com.model.rental.tables.Address;
import com.model.rental.tables.Category;
import com.model.rental.tables.City;
import com.model.rental.tables.Country;
import com.model.rental.tables.Customer;
import com.model.rental.tables.Film;
import com.model.rental.tables.FilmActor;
import com.model.rental.tables.FilmCategory;
import com.model.rental.tables.Inventory;
import com.model.rental.tables.Language;
import com.model.rental.tables.Payment;
import com.model.rental.tables.Rental;
import com.model.rental.tables.RewardsReport;
import com.model.rental.tables.Staff;
import com.model.rental.tables.Store;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Integer> IDENTITY_ACTOR = Identities0.IDENTITY_ACTOR;
    public static final Identity<Record, Integer> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
    public static final Identity<Record, Integer> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
    public static final Identity<Record, Integer> IDENTITY_CITY = Identities0.IDENTITY_CITY;
    public static final Identity<Record, Integer> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;
    public static final Identity<Record, Integer> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<Record, Integer> IDENTITY_FILM = Identities0.IDENTITY_FILM;
    public static final Identity<Record, Integer> IDENTITY_INVENTORY = Identities0.IDENTITY_INVENTORY;
    public static final Identity<Record, Integer> IDENTITY_LANGUAGE = Identities0.IDENTITY_LANGUAGE;
    public static final Identity<Record, Integer> IDENTITY_PAYMENT = Identities0.IDENTITY_PAYMENT;
    public static final Identity<Record, Integer> IDENTITY_RENTAL = Identities0.IDENTITY_RENTAL;
    public static final Identity<Record, Integer> IDENTITY_REWARDS_REPORT = Identities0.IDENTITY_REWARDS_REPORT;
    public static final Identity<Record, Integer> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
    public static final Identity<Record, Integer> IDENTITY_STORE = Identities0.IDENTITY_STORE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> ACTOR_PKEY = UniqueKeys0.ACTOR_PKEY;
    public static final UniqueKey<Record> ADDRESS_PKEY = UniqueKeys0.ADDRESS_PKEY;
    public static final UniqueKey<Record> CATEGORY_PKEY = UniqueKeys0.CATEGORY_PKEY;
    public static final UniqueKey<Record> CITY_PKEY = UniqueKeys0.CITY_PKEY;
    public static final UniqueKey<Record> COUNTRY_PKEY = UniqueKeys0.COUNTRY_PKEY;
    public static final UniqueKey<Record> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
    public static final UniqueKey<Record> FILM_PKEY = UniqueKeys0.FILM_PKEY;
    public static final UniqueKey<Record> FILM_ACTOR_PKEY = UniqueKeys0.FILM_ACTOR_PKEY;
    public static final UniqueKey<Record> FILM_CATEGORY_PKEY = UniqueKeys0.FILM_CATEGORY_PKEY;
    public static final UniqueKey<Record> INVENTORY_PKEY = UniqueKeys0.INVENTORY_PKEY;
    public static final UniqueKey<Record> LANGUAGE_PKEY = UniqueKeys0.LANGUAGE_PKEY;
    public static final UniqueKey<Record> PAYMENT_PKEY = UniqueKeys0.PAYMENT_PKEY;
    public static final UniqueKey<Record> RENTAL_PKEY = UniqueKeys0.RENTAL_PKEY;
    public static final UniqueKey<Record> STAFF_PKEY = UniqueKeys0.STAFF_PKEY;
    public static final UniqueKey<Record> STORE_PKEY = UniqueKeys0.STORE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> ADDRESS__FK_ADDRESS_CITY = ForeignKeys0.ADDRESS__FK_ADDRESS_CITY;
    public static final ForeignKey<Record, Record> CITY__FK_CITY = ForeignKeys0.CITY__FK_CITY;
    public static final ForeignKey<Record, Record> CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY = ForeignKeys0.CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY;
    public static final ForeignKey<Record, Record> FILM__FILM_LANGUAGE_ID_FKEY = ForeignKeys0.FILM__FILM_LANGUAGE_ID_FKEY;
    public static final ForeignKey<Record, Record> FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY = ForeignKeys0.FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY;
    public static final ForeignKey<Record, Record> FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY = ForeignKeys0.FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY;
    public static final ForeignKey<Record, Record> FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY = ForeignKeys0.FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY;
    public static final ForeignKey<Record, Record> FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY = ForeignKeys0.FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY;
    public static final ForeignKey<Record, Record> INVENTORY__INVENTORY_FILM_ID_FKEY = ForeignKeys0.INVENTORY__INVENTORY_FILM_ID_FKEY;
    public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_CUSTOMER_ID_FKEY;
    public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_STAFF_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_STAFF_ID_FKEY;
    public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_RENTAL_ID_FKEY;
    public static final ForeignKey<Record, Record> RENTAL__RENTAL_INVENTORY_ID_FKEY = ForeignKeys0.RENTAL__RENTAL_INVENTORY_ID_FKEY;
    public static final ForeignKey<Record, Record> RENTAL__RENTAL_CUSTOMER_ID_FKEY = ForeignKeys0.RENTAL__RENTAL_CUSTOMER_ID_FKEY;
    public static final ForeignKey<Record, Record> RENTAL__RENTAL_STAFF_ID_KEY = ForeignKeys0.RENTAL__RENTAL_STAFF_ID_KEY;
    public static final ForeignKey<Record, Record> STAFF__STAFF_ADDRESS_ID_FKEY = ForeignKeys0.STAFF__STAFF_ADDRESS_ID_FKEY;
    public static final ForeignKey<Record, Record> STORE__STORE_MANAGER_STAFF_ID_FKEY = ForeignKeys0.STORE__STORE_MANAGER_STAFF_ID_FKEY;
    public static final ForeignKey<Record, Record> STORE__STORE_ADDRESS_ID_FKEY = ForeignKeys0.STORE__STORE_ADDRESS_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Integer> IDENTITY_ACTOR = Internal.createIdentity(Actor.ACTOR, Actor.ACTOR.ACTOR_ID);
        public static Identity<Record, Integer> IDENTITY_ADDRESS = Internal.createIdentity(Address.ADDRESS, Address.ADDRESS.ADDRESS_ID);
        public static Identity<Record, Integer> IDENTITY_CATEGORY = Internal.createIdentity(Category.CATEGORY, Category.CATEGORY.CATEGORY_ID);
        public static Identity<Record, Integer> IDENTITY_CITY = Internal.createIdentity(City.CITY, City.CITY.CITY_ID);
        public static Identity<Record, Integer> IDENTITY_COUNTRY = Internal.createIdentity(Country.COUNTRY, Country.COUNTRY.COUNTRY_ID);
        public static Identity<Record, Integer> IDENTITY_CUSTOMER = Internal.createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.CUSTOMER_ID);
        public static Identity<Record, Integer> IDENTITY_FILM = Internal.createIdentity(Film.FILM, Film.FILM.FILM_ID);
        public static Identity<Record, Integer> IDENTITY_INVENTORY = Internal.createIdentity(Inventory.INVENTORY, Inventory.INVENTORY.INVENTORY_ID);
        public static Identity<Record, Integer> IDENTITY_LANGUAGE = Internal.createIdentity(Language.LANGUAGE, Language.LANGUAGE.LANGUAGE_ID);
        public static Identity<Record, Integer> IDENTITY_PAYMENT = Internal.createIdentity(Payment.PAYMENT, Payment.PAYMENT.PAYMENT_ID);
        public static Identity<Record, Integer> IDENTITY_RENTAL = Internal.createIdentity(Rental.RENTAL, Rental.RENTAL.RENTAL_ID);
        public static Identity<Record, Integer> IDENTITY_REWARDS_REPORT = Internal.createIdentity(RewardsReport.REWARDS_REPORT, RewardsReport.REWARDS_REPORT.CUSTOMER_ID);
        public static Identity<Record, Integer> IDENTITY_STAFF = Internal.createIdentity(Staff.STAFF, Staff.STAFF.STAFF_ID);
        public static Identity<Record, Integer> IDENTITY_STORE = Internal.createIdentity(Store.STORE, Store.STORE.STORE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> ACTOR_PKEY = Internal.createUniqueKey(Actor.ACTOR, "actor_pkey", Actor.ACTOR.ACTOR_ID);
        public static final UniqueKey<Record> ADDRESS_PKEY = Internal.createUniqueKey(Address.ADDRESS, "address_pkey", Address.ADDRESS.ADDRESS_ID);
        public static final UniqueKey<Record> CATEGORY_PKEY = Internal.createUniqueKey(Category.CATEGORY, "category_pkey", Category.CATEGORY.CATEGORY_ID);
        public static final UniqueKey<Record> CITY_PKEY = Internal.createUniqueKey(City.CITY, "city_pkey", City.CITY.CITY_ID);
        public static final UniqueKey<Record> COUNTRY_PKEY = Internal.createUniqueKey(Country.COUNTRY, "country_pkey", Country.COUNTRY.COUNTRY_ID);
        public static final UniqueKey<Record> CUSTOMER_PKEY = Internal.createUniqueKey(Customer.CUSTOMER, "customer_pkey", Customer.CUSTOMER.CUSTOMER_ID);
        public static final UniqueKey<Record> FILM_PKEY = Internal.createUniqueKey(Film.FILM, "film_pkey", Film.FILM.FILM_ID);
        public static final UniqueKey<Record> FILM_ACTOR_PKEY = Internal.createUniqueKey(FilmActor.FILM_ACTOR, "film_actor_pkey", FilmActor.FILM_ACTOR.ACTOR_ID, FilmActor.FILM_ACTOR.FILM_ID);
        public static final UniqueKey<Record> FILM_CATEGORY_PKEY = Internal.createUniqueKey(FilmCategory.FILM_CATEGORY, "film_category_pkey", FilmCategory.FILM_CATEGORY.FILM_ID, FilmCategory.FILM_CATEGORY.CATEGORY_ID);
        public static final UniqueKey<Record> INVENTORY_PKEY = Internal.createUniqueKey(Inventory.INVENTORY, "inventory_pkey", Inventory.INVENTORY.INVENTORY_ID);
        public static final UniqueKey<Record> LANGUAGE_PKEY = Internal.createUniqueKey(Language.LANGUAGE, "language_pkey", Language.LANGUAGE.LANGUAGE_ID);
        public static final UniqueKey<Record> PAYMENT_PKEY = Internal.createUniqueKey(Payment.PAYMENT, "payment_pkey", Payment.PAYMENT.PAYMENT_ID);
        public static final UniqueKey<Record> RENTAL_PKEY = Internal.createUniqueKey(Rental.RENTAL, "rental_pkey", Rental.RENTAL.RENTAL_ID);
        public static final UniqueKey<Record> STAFF_PKEY = Internal.createUniqueKey(Staff.STAFF, "staff_pkey", Staff.STAFF.STAFF_ID);
        public static final UniqueKey<Record> STORE_PKEY = Internal.createUniqueKey(Store.STORE, "store_pkey", Store.STORE.STORE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<Record, Record> ADDRESS__FK_ADDRESS_CITY = Internal.createForeignKey(com.model.rental.Keys.CITY_PKEY, Address.ADDRESS, "address__fk_address_city", Address.ADDRESS.CITY_ID);
        public static final ForeignKey<Record, Record> CITY__FK_CITY = Internal.createForeignKey(com.model.rental.Keys.COUNTRY_PKEY, City.CITY, "city__fk_city", City.CITY.COUNTRY_ID);
        public static final ForeignKey<Record, Record> CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.ADDRESS_PKEY, Customer.CUSTOMER, "customer__customer_address_id_fkey", Customer.CUSTOMER.ADDRESS_ID);
        public static final ForeignKey<Record, Record> FILM__FILM_LANGUAGE_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.LANGUAGE_PKEY, Film.FILM, "film__film_language_id_fkey", Film.FILM.LANGUAGE_ID);
        public static final ForeignKey<Record, Record> FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.ACTOR_PKEY, FilmActor.FILM_ACTOR, "film_actor__film_actor_actor_id_fkey", FilmActor.FILM_ACTOR.ACTOR_ID);
        public static final ForeignKey<Record, Record> FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.FILM_PKEY, FilmActor.FILM_ACTOR, "film_actor__film_actor_film_id_fkey", FilmActor.FILM_ACTOR.FILM_ID);
        public static final ForeignKey<Record, Record> FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.FILM_PKEY, FilmCategory.FILM_CATEGORY, "film_category__film_category_film_id_fkey", FilmCategory.FILM_CATEGORY.FILM_ID);
        public static final ForeignKey<Record, Record> FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.CATEGORY_PKEY, FilmCategory.FILM_CATEGORY, "film_category__film_category_category_id_fkey", FilmCategory.FILM_CATEGORY.CATEGORY_ID);
        public static final ForeignKey<Record, Record> INVENTORY__INVENTORY_FILM_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.FILM_PKEY, Inventory.INVENTORY, "inventory__inventory_film_id_fkey", Inventory.INVENTORY.FILM_ID);
        public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_CUSTOMER_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.CUSTOMER_PKEY, Payment.PAYMENT, "payment__payment_customer_id_fkey", Payment.PAYMENT.CUSTOMER_ID);
        public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_STAFF_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.STAFF_PKEY, Payment.PAYMENT, "payment__payment_staff_id_fkey", Payment.PAYMENT.STAFF_ID);
        public static final ForeignKey<Record, Record> PAYMENT__PAYMENT_RENTAL_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.RENTAL_PKEY, Payment.PAYMENT, "payment__payment_rental_id_fkey", Payment.PAYMENT.RENTAL_ID);
        public static final ForeignKey<Record, Record> RENTAL__RENTAL_INVENTORY_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.INVENTORY_PKEY, Rental.RENTAL, "rental__rental_inventory_id_fkey", Rental.RENTAL.INVENTORY_ID);
        public static final ForeignKey<Record, Record> RENTAL__RENTAL_CUSTOMER_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.CUSTOMER_PKEY, Rental.RENTAL, "rental__rental_customer_id_fkey", Rental.RENTAL.CUSTOMER_ID);
        public static final ForeignKey<Record, Record> RENTAL__RENTAL_STAFF_ID_KEY = Internal.createForeignKey(com.model.rental.Keys.STAFF_PKEY, Rental.RENTAL, "rental__rental_staff_id_key", Rental.RENTAL.STAFF_ID);
        public static final ForeignKey<Record, Record> STAFF__STAFF_ADDRESS_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.ADDRESS_PKEY, Staff.STAFF, "staff__staff_address_id_fkey", Staff.STAFF.ADDRESS_ID);
        public static final ForeignKey<Record, Record> STORE__STORE_MANAGER_STAFF_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.STAFF_PKEY, Store.STORE, "store__store_manager_staff_id_fkey", Store.STORE.MANAGER_STAFF_ID);
        public static final ForeignKey<Record, Record> STORE__STORE_ADDRESS_ID_FKEY = Internal.createForeignKey(com.model.rental.Keys.ADDRESS_PKEY, Store.STORE, "store__store_address_id_fkey", Store.STORE.ADDRESS_ID);
    }
}
