/*
 * This file is generated by jOOQ.
 */
package com.model.rental;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>actor_actor_id_seq</code>
     */
    public static final Sequence<Long> ACTOR_ACTOR_ID_SEQ = new SequenceImpl<Long>("actor_actor_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>address_address_id_seq</code>
     */
    public static final Sequence<Long> ADDRESS_ADDRESS_ID_SEQ = new SequenceImpl<Long>("address_address_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>category_category_id_seq</code>
     */
    public static final Sequence<Long> CATEGORY_CATEGORY_ID_SEQ = new SequenceImpl<Long>("category_category_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>city_city_id_seq</code>
     */
    public static final Sequence<Long> CITY_CITY_ID_SEQ = new SequenceImpl<Long>("city_city_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>country_country_id_seq</code>
     */
    public static final Sequence<Long> COUNTRY_COUNTRY_ID_SEQ = new SequenceImpl<Long>("country_country_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>customer_customer_id_seq</code>
     */
    public static final Sequence<Long> CUSTOMER_CUSTOMER_ID_SEQ = new SequenceImpl<Long>("customer_customer_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>film_film_id_seq</code>
     */
    public static final Sequence<Long> FILM_FILM_ID_SEQ = new SequenceImpl<Long>("film_film_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>inventory_inventory_id_seq</code>
     */
    public static final Sequence<Long> INVENTORY_INVENTORY_ID_SEQ = new SequenceImpl<Long>("inventory_inventory_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>language_language_id_seq</code>
     */
    public static final Sequence<Long> LANGUAGE_LANGUAGE_ID_SEQ = new SequenceImpl<Long>("language_language_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>payment_payment_id_seq</code>
     */
    public static final Sequence<Long> PAYMENT_PAYMENT_ID_SEQ = new SequenceImpl<Long>("payment_payment_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>rental_rental_id_seq</code>
     */
    public static final Sequence<Long> RENTAL_RENTAL_ID_SEQ = new SequenceImpl<Long>("rental_rental_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>staff_staff_id_seq</code>
     */
    public static final Sequence<Long> STAFF_STAFF_ID_SEQ = new SequenceImpl<Long>("staff_staff_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>store_store_id_seq</code>
     */
    public static final Sequence<Long> STORE_STORE_ID_SEQ = new SequenceImpl<Long>("store_store_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
